name: debug-VLAD-deploy

on:
  push:
    branches: [ "debug_VLAD" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ftp-deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: f1176550.xsph.ru
          username: mloptimizerdeveloper@f1176550
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./debug_VLAD/
          exclude: |
            **/.git*
            **/.git*/**
            README.md
