name: web-deploy

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ftp-deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp://f1176550.xsph.ru
          username: f1176550
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./domains/f1176550.xsph.ru/public_html/ml_optimizer
